---
.github/CONTRIBUTING.md:
  delete: true

.github/ISSUE_TEMPLATE.md:
  delete: true

.github/PULL_REQUEST_TEMPLATE.md:
  delete: true

.gitlab-ci.yml:
  delete: true

.travis.yml:
  remove_branches:
    - main
    - /^v\d/
  docker_sets:
    - set: debian9-64
    - set: debian10-64
    - set: ubuntu1804-64
    - set: centos7-64
  irc: false
  user: 'deric'
  secure: 'K3gfvfUtsZ4l6TTChG5jBLIB4j9ZG3zQECBCMI0ZcYiyiFYIihDtraO6sTf0qOcocRg5TpihBNJ8IpBPdDvd8bOrQCIWnSor2hP6NKA8J0XCDX5H4hmyieJhFCuGydaopia6rATEbj4TIOzMk8zPVc/lavg4yRkpwcxCy7UQVKc='

Rakefile:
  config.user: 'deric'

spec/spec_helper.rb:
  spec_overrides: "require 'spec_helper_local' if File.file?(File.join(File.dirname(__FILE__), 'spec_helper_local.rb'))"

Gemfile:
  required:
    ":development":
      - gem: 'overcommit'
  optional:
    ':acceptance':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-docker
      - gem: beaker-puppet_install_helper
      - gem: beaker-module_install_helper
